### ISSUE TITLE
NA in probability vector

### ISSUE THREAD

**Issue by JasperHG90** [emmekeaarts/mHMMbayes#10]
One of my iterations yields the following error:

![image](https://user-images.githubusercontent.com/8079803/76529394-82b26480-6472-11ea-93a9-cc68edb1c73e.png)

This seems to be related to bad start values, but I'm not sure how entirely. I played around with it a little bit, and I think that it occurs when a user passes start values for an emission distribution where the residual error is very tiny, e.g.

```r
        [,1]   [,2]
[1,]  0.5615 0.1416
[2,] -0.7668 0.0049
[3,]  0.5309 0.0052
``` 

Running the model with this setting yields an error. With larger variances, it does not. 

Does not seem to yield this error with other emission distributions with small variances however. 

Anyway. Maybe you'd say: "makes sense. What distribution has a variance of near 0?". 

Perhaps build in a check that makes sure that users don't try to do this? Error confused me quite a bit at first.

**Comment by aaubry89** [comment]
I am also having this problem and changing the probabilities doesn't seem to help. Did you make any progress on finding what specifically causes this error?

**Comment by emmekeaarts** [comment]
The latest version of the package checks for this, and throws an error explaining the problem: 
"starting values that do not match the data were specified, e.g., using means and (too small) standard deviations that do not sufficiently support the full range of the observed data (i.e., resulting in observation(s) that have an extremely small probability of being observed)".
