### ISSUE TITLE
 Time-varing covariates for predicting the transition matrix and the emission probabilities

### ISSUE THREAD

**Issue by DanielGaohongming** [emmekeaarts/mHMMbayes#11]
Hi, Emmeke,
    Thanks for your efforts! the mHMMbayes is a wonderful masterpiece. 
    I learned that the mHMM is able to deal with individual heterogeneity, by time-invariant covariates. Could you kindly let me know whether the function mHMM could include time-varying covariates to predict the transition matrix and the emission probabilities? 
 
   

Best regards,
Hongming

**Comment by emmekeaarts** [comment]
Hi Hongming, 

This is still under development, but In the development branch time-vary-cov, you can find a function mHMM_cat_tv(), which fits a multilevel hidden Markov model (HMM) with ONE time varying covariate to predict gamma. Please note that this function is currently restricted to categorical observations only, and the (one) time varying covariate can only be used to predict the transition probabilities gamma. 

Best regards, 
Emmeke
