### ISSUE TITLE
Model takes too long to run without showing progress bar

### ISSUE THREAD

**Issue by mmervecerit** [emmekeaarts/mHMMbayes#23]
Hi, I was wondering whether you have runtime benchmarks on fitting mhmm on different-sized data. 

I am running mhmm on more than a total of 100M observations with 25 time-invariant covariates; that's why I am expecting my model to fit in a long time, however, with J=11 and burn_in=5 on a local M1 machine, I couldn't even see the progress bar in 4 hours, and wanted to check-in.  

Thanks!

**Comment by emmekeaarts** [comment]
Hi, no I must admit that I unfortunately do not have those, however I must say that you are pushing the model to the boundary compared to what I have tested and used it on :) You could try to get an indication by only using a subset of the data (less observations per subject), or simulated data that resembles your own using the function sim_mHMM()? In addition, note that how many time-invariant covariates it can handle reliably is driven by the number of subjects included, and not the number of observations per subject, as these are level 2 variables
