### ISSUE TITLE
dif_matrix in vit_mHMM line 126 and 127

### ISSUE THREAD

**Issue by wiesnerfriedman** [emmekeaarts/mHMMbayes#26]
I'm confused about where the dif_matrix is coming from in the function vit_mHMM. I was trying to use the code to get the probabilities associated with each state for each subject and was not able to run the code on its own. What am I missing here?

**Comment by marrti-go** [comment]
I think you should run utility_function_mHMM.R  first, the dif_matrix function is there.

**Comment by wiesnerfriedman** [comment]
Thank you! I found all the source functions. I guess because of the way the package is compiled, if I want to try to edit the functions (without knowing much C++), I just have to build the package after edits to the function. I am interested in the forward calculated posterior distributions at each time point t and would also be interested in a measure of variance around that. I have been looking through the C++ code to figure out how I would do this. Would you be able to help?

**Comment by emmekeaarts** [comment]
The current version of the package now also returns the forward probabilities when desired when using the function vit_mHMM(), in addition to the most likely state at each time point. I hope this already helps, including a measure of variance around that would be quite complicated I'm afraid, but please contact me again if you have any ideas on this!
