### ISSUE TITLE
Cannot run vit_mHMM on continuous mHMM

### ISSUE THREAD

**Issue by Skillmerism** [emmekeaarts/mHMMbayes#31]
I am attempting to run vit_mHMM with a continuous mHMM, but I keep receiving the following error: 

Error in state_seq[1:n_vary[s], s] <- apply(probs[[s]], 2, which.max) : 
  number of items to replace is not a multiple of replacement length

I don't understand why the error is occurring, as my data is entirely numeric (except for the ID column which is integer) and follows the same format as shown in the documentation. The mHMM function ran perfectly as well. I've added a sample of my data below and the result from summary(mHMM). Any ideas on why this is happening and how to fix it?

tibble [3,483 × 4] (S3: tbl_df/tbl/data.frame)
 $ id      : int [1:3483] 1 2 3 4 5 6 7 8 9 10 ...
 $ MouseID1: num [1:3483] 36.3 36.2 36.7 36.7 36.8 ...
 $ MouseID2: num [1:3483] 36.9 37 37.1 37.1 37.1 ...
 $ MouseID3: num [1:3483] 36.4 36.4 36.5 36.7 36.9 ...

State transition probability matrix 
 (at the group level): 
 
To state 1 To state 2 To state 3 To state 4 To state 5 To state 6 To state 7
From state 1      0.131      0.145      0.068      0.095      0.204      0.120      0.236
From state 2      0.076      0.533      0.194      0.085      0.041      0.030      0.040
From state 3      0.089      0.124      0.444      0.167      0.086      0.046      0.044
From state 4      0.096      0.100      0.122      0.432      0.068      0.081      0.101
From state 5      0.045      0.035      0.781      0.068      0.022      0.034      0.015
From state 6      0.106      0.302      0.084      0.075      0.071      0.249      0.112
From state 7      0.073      0.050      0.194      0.020      0.055      0.054      0.555

 
Emission distribution ( continuous ) for each of the dependent variables 
 (at the group level): 
 
$MouseID1
          Mean    SD
State 1 19.027 1.242
State 2 51.005 1.223
State 3 35.408 1.178
State 4 31.738 1.224
State 5 47.401 1.241
State 6 41.061 1.221
State 7 35.605 1.166

$MouseID2
          Mean    SD
State 1 18.936 1.089
State 2 63.290 1.076
State 3 38.212 1.024
State 4 28.604 1.073
State 5 67.306 1.099
State 6 33.131 1.088
State 7 30.816 1.091

$MouseID3
          Mean    SD
State 1 18.821 1.145
State 2 71.993 1.124
State 3 44.017 1.114
State 4     NA    NA
State 5 69.708 1.154
State 6 39.597 1.119
State 7     NA    NA

**Comment by emmekeaarts** [comment]
This must be because of the NAs in the mouse specific emission distributions (for example, for mouse 3), I don't completely understand why that happens though.. If you write me an email at e.aarts[at]uu.nl, we can try to solve it digging in bit deeper.
