### ISSUE TITLE
The correct way to specify hyperparameter values when using mhmm_cont

### ISSUE THREAD

**Issue by JasperHG90** [emmekeaarts/mHMMbayes#7]
The mHMM_cont() function requires the user to specify hyperprior distribution parameters. 

From the documentation, it is suggested that this should be a list containing named elements for each hyperparameter. Each of the elements then contains the values for each dependent variable and/or each latent state. For example, for `emiss_mu0`, it says:

> "a list containing n_dep vectors with length m, i.e., one for each dependent variable k. Each matrix for each set of emission probabilities within a state. The matrices contain the hypothesized mean values of the intercepts. Hence, each matrix consists of one row (when not including covariates in the model) and q_emiss[k] - 1 columns"

Which leads me to create a list with k entries (k being the number of dependent variables). Each entry is an unnamed m-length vector, where m is the number of hidden states. e.g.

```r
emiss_mu0 = list(
    # Depvar1
    c(-5, -1, 5),
    # Depvar2
    c(-10, 1, 10),
    # Depvar3
    c(-20, -0.3, 20),
    # Depvar4
    c(8,-8,0)
)
```

But the [code check](https://github.com/JasperHG90/mHMMbayes/blob/69ec4466825a19c6f88b2ceab357cf31ac964987/R/mHMM_cont.R#L508-L516) does this:

```r
 hyperparam_list[[k]]$emiss_mu0
```

This suggests that, at the first level, the hyperparameter list is in fact a k-length list, each element of which is either a named vector or a named list with the value of each of the hyperparameters.

Which of the two approaches is desired?

**Comment by emmekeaarts** [comment]
Thank you for pointing this out! The specification in the manual is preferred, so the code was incorrect. The code is now fixed.
