### ISSUE TITLE
Error 'q_emiss' not found when running mHMM_cont

### ISSUE THREAD

**Issue by JasperHG90** [emmekeaarts/mHMMbayes#8]
mHMM_cont() requires the following parameters:

> mHMM_cont(s_data, gen, xx = NULL, start_val, emiss_hyp_prior, mcmc,
>  return_path = FALSE, print_iter, show_progress = TRUE,
>  gamma_hyp_prior = NULL, gamma_sampler = NULL)

But running this function with all required arguments yields the following error:

```
Error in lapply(q_emiss + q_emiss - 1 + 1, dif_matrix, rows = (J - 1) *  : 
  object 'q_emiss' not found
```

Probably in [line 535](https://github.com/emmekeaarts/mHMMbayes/blob/develop/R/mHMM_cont.R#L535). A reference to q_emiss is also given in [line 498](https://github.com/emmekeaarts/mHMMbayes/blob/develop/R/mHMM_cont.R#L498). My guess is that this is an artifact from porting the function from the categorical version.

**Comment by emmekeaarts** [comment]
Yes, thank you for pointing this out, this issue is now solved.
